### ISSUE TITLE
We should be more conservative with hosting video content

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra-docs#62]
Ideally, all video should be hosted elsewhere, say on YouTube, on BlackFoundry's channel.

Video's that already exist under our control on YouTube can be referenced with a time indicator, so we do not need to upload more raw video (which makes the repo heavier than needed).

Example: the video on [this page](https://docs.fontra.xyz/reference/panels/related-glyphs-and-characters) should be an embedded YT video with a time indicator.

(Spammy site with examples of how to add a timestamp to a YT video: https://www.wikihow.com/Link-to-a-Certain-Time-in-a-YouTube-Video)

**Comment by justvanrossum** [comment]
Likewise for the video on this page: https://docs.fontra.xyz/how-tos/draw/designing-with-variable-components

We really shouldn't maintain such massive video files as part of the repo.

**Comment by ollimeier** [comment]
@justvanrossum Whenever I can I try NOT to use YouTube on our docs page, because YouTube is blocked for people from (for example) China. At least that's the reason why I tried not to use it. My hope is that this way we can give more people access. 
Or do I overthink things here?

**Comment by justvanrossum** [comment]
That is a good point.

**Comment by ollimeier** [comment]
I am closing this, because it has a reason why we store our own content.
