### ISSUE TITLE
Add information about background images

### ISSUE THREAD

**Issue by ollimeier** [googlefonts/fontra-docs#70]
New feature 'background images'

**Comment by justvanrossum** [comment]
You were a bit too quick on this: the screen recordings are already out of date because the colorization feature has been added...

**Comment by ollimeier** [comment]
> You were a bit too quick on this: the screen recordings are already out of date because the colorization feature has been added...

I was actually aware of that and it was intentionally – because I know you don't like working with "docs", I published it even though one gif needs to be replace once the missing feature is in place. This way you don't have to build the docs page locally on your machine and can have a look and review in the "regular" homepage and probably give me feedback till today. I replaced the one gif (the others do no show the "Colorized" feature). So I am closing this again. Feel free to reopen it, if there is anything else, but please keep in mind, that I won't work next.
